In [5]:
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [6]:
import sys
!{sys.executable} -m pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-20.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Downloading pyarrow-20.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (42.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 MB 58.6 MB/s eta 0:00:000m eta 0:00:01
Installing collected packages: pyarrow
Successfully installed pyarrow-20.0.0

In [7]:
df = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet')

In [8]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186,79,2,17.7,1.0,0.5,0.00,0.0,1.0,22.70,2.5,0.0
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140,236,1,10.0,3.5,0.5,3.75,0.0,1.0,18.75,2.5,0.0
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236,79,1,23.3,3.5,0.5,3.00,0.0,1.0,31.30,2.5,0.0
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79,211,1,10.0,3.5,0.5,2.00,0.0,1.0,17.00,2.5,0.0
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211,148,1,7.9,3.5,0.5,3.20,0.0,1.0,16.10,2.5,0.0

In [9]:
!pip list

Package                 Version
----------------------- -----------
anaconda-anon-usage     0.4.4
archspec                0.2.3
boltons                 23.0.0
Bottleneck              1.4.2
Brotli                  1.0.9
certifi                 2025.6.15
cffi                    1.16.0
charset-normalizer      2.0.4
conda                   24.11.3
conda-content-trust     0.2.0
conda-libmamba-solver   24.1.0
conda-package-handling  2.2.0
conda_package_streaming 0.9.0
cramjam                 2.10.0
cryptography            42.0.5
distro                  1.9.0
fastparquet             2024.11.0
frozendict              2.4.2
fsspec                  2025.5.1
idna                    3.7
jsonpatch               1.33
jsonpointer             2.1
libmambapy              1.5.8
menuinst                2.0.2
mkl_fft                 1.3.11
mkl_random              1.2.8
mkl-service             2.4.0
numexpr                 2.10.1
numpy                   2.2.5
packaging               23.2
pandas                  2.2.3
pip                     24.0
platformdirs            3.10.0
pluggy                  1.0.0
pyarrow                 19.0.0
pycosat                 0.6.6
pycparser               2.21
PySocks                 1.7.1
python-dateutil         2.9.0.post0
pytz                    2024.1
requests                2.31.0
ruamel.yaml             0.17.21
ruamel.yaml.clib        0.2.6
setuptools              69.5.1
six                     1.17.0
tqdm                    4.66.2
truststore              0.8.0
tzdata                  2025.2
urllib3                 2.1.0
wheel                   0.43.0
zstandard               0.22.0